### ISSUE TITLE
Create GFBio mailing list for ontology development

### ISSUE THREAD

**Issue by cpfaff** [gfbio/gfbio-ontology#14]
Who is responsible to set up the mailing lists?

**Comment by cpfaff** [comment]
That has been requested form @uschindler today. The wiki already contains the links to mailmain.

**Comment by DavidFichtmueller** [comment]
I have checked back with Uwe again yesterday, it must have slipped through. Now the mailing list is ready to use.

**Comment by uschindler** [comment]
Sorry the mail got lost. I had too much to do around xmas.
